"""Safe fast-forward updates for editable source installations."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shutil
import subprocess
import sys
from typing import Protocol

from packaging.version import Version

from . import Installation, InstallMode


class SourceUpdateError(RuntimeError):
    """Raised when a source checkout cannot be updated safely."""


@dataclass(frozen=True)
class CommandResult:
    """Captured result of one trusted source-update command."""

    returncode: int
    stdout: str = ""
    stderr: str = ""


class SourceCommandRunner(Protocol):
    """Boundary for commands generated by SourceUpdater."""

    def run(self, command: list[str], *, cwd: Path) -> CommandResult:
        """Run command without a shell and capture its result."""


class SubprocessSourceCommandRunner:
    """Execute trusted Git, Python, and Bun commands."""

    def run(self, command: list[str], *, cwd: Path) -> CommandResult:
        """Run one trusted source command without a shell."""

        completed = subprocess.run(
            command,
            cwd=cwd,
            capture_output=True,
            check=False,
            shell=False,
            text=True,
        )
        return CommandResult(completed.returncode, completed.stdout, completed.stderr)


@dataclass(frozen=True)
class SourceUpdateResult:
    """Summary of a completed source update."""

    previous_commit: str
    target_commit: str
    frontend_dependencies_refreshed: bool


_FRONTEND_LOCKS = (
    "web/bun.lock",
    "web/bun.lockb",
    "web/package-lock.json",
)


class SourceUpdater:
    """Fast-forward one clean editable checkout to a stable release tag."""

    def __init__(
        self,
        *,
        runner: SourceCommandRunner | None = None,
        python_executable: str | None = None,
        bun_executable: str | None = None,
    ) -> None:
        self._runner = runner or SubprocessSourceCommandRunner()
        self._python = python_executable or sys.executable
        self._bun = bun_executable

    def update(
        self,
        installation: Installation,
        target_version: str,
    ) -> SourceUpdateResult:
        """Apply a stable source update or refuse before changing the checkout."""

        if installation.mode not in {InstallMode.SOURCE_WEB, InstallMode.SOURCE_CLI}:
            raise SourceUpdateError("This is not an editable source installation")
        if installation.source_root is None:
            raise SourceUpdateError("The editable source root is unavailable")

        source_root = installation.source_root.resolve()
        editable_root = (
            source_root
            if installation.mode is InstallMode.SOURCE_WEB
            else source_root / "packaging" / "deeptutor-cli"
        )
        if not (editable_root / "pyproject.toml").is_file():
            raise SourceUpdateError("The editable source project is incomplete")

        version = Version(target_version)
        if version.is_prerelease or version.is_devrelease:
            raise SourceUpdateError("The source update target must be stable")
        tag = f"v{version}"

        repository_root = Path(
            self._git_required(
                source_root,
                ["rev-parse", "--show-toplevel"],
                "Git checkout",
            )
        ).resolve()
        if repository_root != source_root:
            raise SourceUpdateError("The editable source root is not the Git checkout root")

        branch_result = self._git(
            source_root,
            ["symbolic-ref", "--quiet", "--short", "HEAD"],
        )
        if branch_result.returncode != 0 or not branch_result.stdout.strip():
            raise SourceUpdateError("Source update refused: detached HEAD")
        branch = branch_result.stdout.strip()
        self._require_clean(source_root)
        previous_commit = self._git_required(
            source_root,
            ["rev-parse", "HEAD"],
            "current source revision",
        )

        upstream = self._git_required(
            source_root,
            ["rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}"],
            "configured upstream branch",
        )
        remote = self._git_required(
            source_root,
            ["config", "--get", f"branch.{branch}.remote"],
            "configured upstream remote",
        )
        if remote == ".":
            raise SourceUpdateError("Source update requires a configured remote upstream")

        self._git_required(
            source_root,
            ["fetch", "--no-tags", remote],
            "upstream fetch",
            allow_empty=True,
        )
        self._git_required(
            source_root,
            ["fetch", "--no-tags", remote, f"refs/tags/{tag}:refs/tags/{tag}"],
            f"stable release tag {tag}",
            allow_empty=True,
        )

        current_branch = self._git_required(
            source_root,
            ["symbolic-ref", "--quiet", "--short", "HEAD"],
            "current branch",
        )
        if current_branch != branch:
            raise SourceUpdateError("Source branch changed while checking for updates")
        self._require_clean(source_root)
        if (
            self._git_required(
                source_root,
                ["rev-parse", "HEAD"],
                "current revision",
            )
            != previous_commit
        ):
            raise SourceUpdateError("Source revision changed while checking for updates")

        counts = self._git_required(
            source_root,
            ["rev-list", "--left-right", "--count", f"HEAD...{upstream}"],
            "upstream branch comparison",
        ).split()
        if len(counts) != 2:
            raise SourceUpdateError("Unable to compare the configured upstream branch")
        try:
            local_only, upstream_only = (int(value) for value in counts)
        except ValueError as exc:
            raise SourceUpdateError("Unable to compare the configured upstream branch") from exc
        if local_only and upstream_only:
            raise SourceUpdateError("Source update refused: branch has diverged from upstream")

        target_commit = self._git_required(
            source_root,
            ["rev-parse", "--verify", f"refs/tags/{tag}^{{commit}}"],
            f"stable release tag {tag}",
        )
        ancestor = self._git(
            source_root,
            ["merge-base", "--is-ancestor", previous_commit, target_commit],
        )
        if ancestor.returncode == 1:
            raise SourceUpdateError(
                f"Source update refused: {tag} cannot be fast-forwarded from HEAD"
            )
        if ancestor.returncode != 0:
            self._raise_command_error("release ancestry check", ancestor)

        frontend_changed = False
        if installation.mode is InstallMode.SOURCE_WEB:
            lock_diff = self._git(
                source_root,
                [
                    "diff",
                    "--quiet",
                    previous_commit,
                    target_commit,
                    "--",
                    *_FRONTEND_LOCKS,
                ],
            )
            if lock_diff.returncode not in {0, 1}:
                self._raise_command_error("frontend lock comparison", lock_diff)
            frontend_changed = lock_diff.returncode == 1

        self._required(
            [self._python, "-m", "pip", "--version"],
            cwd=editable_root,
            purpose="Python environment preflight",
        )
        bun = self._bun or shutil.which("bun")
        if frontend_changed:
            if not bun:
                raise SourceUpdateError(
                    "Frontend dependencies changed, but Bun is not available on PATH"
                )
            self._required(
                [bun, "--version"],
                cwd=source_root / "web",
                purpose="Bun preflight",
            )

        self._git_required(
            source_root,
            [
                "pull",
                "--ff-only",
                "--no-rebase",
                "--no-tags",
                remote,
                f"refs/tags/{tag}",
            ],
            f"fast-forward to {tag}",
            allow_empty=True,
        )
        if (
            self._git_required(
                source_root,
                ["rev-parse", "HEAD"],
                "updated revision",
            )
            != target_commit
        ):
            raise SourceUpdateError("Git did not finish at the stable release commit")

        self._required(
            [
                self._python,
                "-m",
                "pip",
                "install",
                "--no-deps",
                "--editable",
                str(editable_root),
            ],
            cwd=editable_root,
            purpose="editable Python refresh",
        )
        if frontend_changed and bun:
            self._required(
                [bun, "install", "--no-save"],
                cwd=source_root / "web",
                purpose="Bun dependency refresh",
            )

        return SourceUpdateResult(
            previous_commit=previous_commit,
            target_commit=target_commit,
            frontend_dependencies_refreshed=frontend_changed,
        )

    def _require_clean(self, source_root: Path) -> None:
        status = self._git_required(
            source_root,
            ["status", "--porcelain=v1", "--untracked-files=all"],
            "working tree status",
            allow_empty=True,
        )
        if status:
            raise SourceUpdateError("Source update refused: working tree is not clean")

    def _git(self, source_root: Path, arguments: list[str]) -> CommandResult:
        return self._run(["git", *arguments], cwd=source_root)

    def _git_required(
        self,
        source_root: Path,
        arguments: list[str],
        purpose: str,
        *,
        allow_empty: bool = False,
    ) -> str:
        result = self._git(source_root, arguments)
        if result.returncode != 0:
            self._raise_command_error(purpose, result)
        output = result.stdout.strip()
        if not output and not allow_empty:
            raise SourceUpdateError(f"Unable to resolve {purpose}")
        return output

    def _required(self, command: list[str], *, cwd: Path, purpose: str) -> None:
        result = self._run(command, cwd=cwd)
        if result.returncode != 0:
            self._raise_command_error(purpose, result)

    def _run(self, command: list[str], *, cwd: Path) -> CommandResult:
        try:
            return self._runner.run(command, cwd=cwd)
        except OSError as exc:
            raise SourceUpdateError(str(exc) or type(exc).__name__) from exc

    @staticmethod
    def _raise_command_error(purpose: str, result: CommandResult) -> None:
        detail = (result.stderr or result.stdout).strip()
        suffix = f": {detail}" if detail else ""
        raise SourceUpdateError(f"Unable to complete {purpose}{suffix}")


def create_source_updater() -> SourceUpdater:
    """Build the production source updater for the active Python environment."""

    return SourceUpdater()


__all__ = (
    "CommandResult",
    "SourceCommandRunner",
    "SourceUpdateError",
    "SourceUpdateResult",
    "SourceUpdater",
    "SubprocessSourceCommandRunner",
    "create_source_updater",
)
