"use client";
import { ChevronsLeft, ChevronsRight } from "lucide-react";
import { useTranslation } from "react-i18next";
import type { LearningPlan, TopicDraft } from "@/lib/learning-api";
import { planBriefEntries } from "@/lib/mastery-planning";

export function PlanningOutline({ plan, draft, collapsed, onToggleCollapsed, onConfirm, busy }: { plan: LearningPlan; draft: TopicDraft | null; collapsed: boolean; onToggleCollapsed: () => void; onConfirm: () => void; busy: boolean }) {
  const { t } = useTranslation();
  if (collapsed) return <button type="button" onClick={onToggleCollapsed} title={t("Show plan outline")} aria-label={t("Show plan outline")} className="flex h-full w-full flex-col items-center gap-2.5 pt-4 text-[var(--muted-foreground)] transition-colors hover:bg-[var(--muted)]/50 hover:text-[var(--foreground)]"><ChevronsRight className="h-4 w-4" /><span className="text-[10px] font-medium uppercase tracking-[0.16em]" style={{ writingMode: "vertical-rl" }}>{t("Plan")}</span></button>;
  const entries = planBriefEntries((plan.brief || plan.input) as unknown as Record<string, unknown>, t);
  return <nav aria-label={t("Plan outline")} className="flex h-full flex-col pb-10"><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-medium uppercase tracking-[0.16em] text-[var(--muted-foreground)]/70">{t("Plan outline")}</span><div className="flex items-center gap-2"><span className="text-[10.5px] tabular-nums text-[var(--muted-foreground)]/55">{draft ? `${draft.modules.length} ${t("modules")}` : t("Brief")}</span><button type="button" onClick={onToggleCollapsed} title={t("Hide plan outline")} aria-label={t("Hide plan outline")} className="flex h-5 w-5 items-center justify-center rounded text-[var(--muted-foreground)]/50 transition-colors hover:bg-[var(--muted)]/60 hover:text-[var(--foreground)]"><ChevronsLeft className="h-3.5 w-3.5" /></button></div></div><div className="mt-5 flex-1 space-y-6 overflow-y-auto">{draft ? draft.modules.map((module, i) => <section key={module.id}><div className="flex items-baseline gap-2"><span className="w-[18px] shrink-0 text-[10.5px] font-medium tabular-nums text-[var(--muted-foreground)]/45">{String(i + 1).padStart(2, "0")}</span><h2 className="min-w-0 text-[12.5px] font-semibold leading-5 text-[var(--foreground)]">{module.name}</h2><span className="ml-auto shrink-0 text-[10px] tabular-nums text-[var(--muted-foreground)]/55">{module.knowledge_points.length}</span></div><ul className="relative mt-1.5 before:absolute before:bottom-[14px] before:left-[21px] before:top-[14px] before:w-px before:bg-[var(--border)]">{module.knowledge_points.map((point) => <li key={point.id}><div className="flex items-start gap-2 rounded-md py-[5px] pl-[18px] pr-2"><span className="relative z-[1] mt-[5px] h-[7px] w-[7px] shrink-0 rounded-full border border-[var(--primary)]/60 bg-[var(--background)]" /><span className="min-w-0 text-[12px] leading-[18px] text-[var(--muted-foreground)]">{point.name}</span></div></li>)}</ul></section>) : <section><h2 className="text-[12.5px] font-semibold leading-5 text-[var(--foreground)]">{t("Plan Brief")}</h2><dl className="mt-3 space-y-3">{entries.map(([label, value]) => <div key={label}><dt className="text-[10px] uppercase tracking-[0.16em] text-[var(--muted-foreground)]/70">{t(label)}</dt><dd className="mt-0.5 whitespace-pre-wrap text-[12px] leading-[18px] text-[var(--foreground)]">{value}</dd></div>)}</dl></section>}<div className="border-t border-[var(--border)] pt-3 text-[11px] text-[var(--muted-foreground)]">{t("Revision {{n}} · {{status}}", { n: plan.brief_revision, status: t(({ discussing: "Planning", settled: "Ready to generate", draft_ready: "Draft ready" } as const)[plan.state]) })}</div></div><button type="button" onClick={onConfirm} disabled={busy} className="mt-4 w-full rounded-xl bg-[var(--primary)] px-3 py-2.5 text-xs font-medium text-[var(--primary-foreground)] disabled:opacity-50">{t("Confirm plan and generate route")}</button></nav>;
}
